# Generated by Django 2.0.2 on 2020-09-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.BigIntegerField(blank=True, null=True)),
                ('study_status', models.SmallIntegerField(choices=[(0, '未毕业'), (1, '已毕业')], default=0)),
                ('school_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school_student', to='search.School')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'text',
                'managed': True,
            },
        ),
    ]
