# Generated by Django 2.0.2 on 2020-09-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
